# This is a basic workflow to help you get started with Actions

name: CI

on: push
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
        - name: Deploy Stage
          uses: satak/webrequest-action@master
          with:
              url: 'https://webhook.site/01513279-f460-4742-8420-e27a9c521596'
              method: POST
              payload: '{"name": "${{ env.MY_NAME }}"}'
