# This is a basic workflow to help you get started with Actions

name: CI

on: push
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
        - name: Deploy Stage
          uses: satak/webrequest-action@master
          with:
              url: 'https://outlook.office.com/webhook/7b9e7bbe-a1d5-4bf0-ab34-fb795559ff72@2c2bb68d-f234-4baa-a640-ede7b35d9620/IncomingWebhook/6569801162bb44c69301e77fb05b3308/0fb58a4f-6a99-4de4-b47c-1fe4dc2d71d2'
              method: POST
              payload: '{"text": "hey ${{ github.actor }}"}'
