# This is a basic workflow to help you get started with Actions

name: CI

on: push
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
        - name: Dump git info
          env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - name: Deploy Stage
          uses: satak/webrequest-action@master
          with:
              url: ${{ secrets.TEAMS_WEBHOOK }}
              method: POST
              payload: '{"text": "New Commit on master of https://github.com/bishrant/MapMyProperty by ${{ github.actor }}"}'
